language: cpp
compiler:
  - clang
  - gcc
before_install:
  - wget ftp://gcc.gnu.org/pub/gcc/infrastructure/gmp-6.1.0.tar.bz2
  - tar xjf gmp-6.1.0.tar.bz2
  - cd gmp-6.1.0
  - ./configure
  - make
  - sudo make install
script:
  - mkdir build
  - cd build
  - cmake -DWITH_FLINT=false -DOMIT_EXAMPLE=true ..
  - make
