language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libgmp-dev
script:
  - mkdir build
  - cd build
  - cmake -DWITH_FLINT=false -DOMIT_EXAMPLE=true ..
  - make
